# Generated by Django 5.2.6 on 2025-09-07 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rev_reply_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администрации'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_reply_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администрации'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_reply_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администрации'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_text_en',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_text_ky',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_text_ru',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_user_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_user_name_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_user_name_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
