# Generated by Django 5.2.6 on 2025-09-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_review_rev_reply_en_review_rev_reply_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название удобства')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='airbnb.amenity', verbose_name='Удобства'),
        ),
    ]
